color_theme = "phosphor"
theme_background = True
truecolor = True
vim_keys = True
rounded_corners = False
graph_symbol = "braille"
graph_symbol_cpu = "braille"
graph_symbol_mem = "braille"
graph_symbol_net = "braille"
graph_symbol_proc = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
proc_per_core = False
proc_gradient = False
cpu_graph_upper = "total"
cpu_graph_lower = "total"
cpu_single_graph = False
show_uptime = True
check_temp = True
show_battery = True
clock_format = "%H:%M"
background_update = True
disks_filter = ""
show_io_stat = False
io_mode = False
net_sync = True
net_auto = True
show_cpu_freq = True
log_level = "WARNING"
